/* See LICENSE file for copyright and license details. */

#ifndef PARSE_RINGBUFFER_MIN_AVAILABLE
# define PARSE_RINGBUFFER_MIN_AVAILABLE 512
#endif

#ifndef PARSE_RINGBUFFER_INCREASE_SIZE
# define PARSE_RINGBUFFER_INCREASE_SIZE 4096
#endif

#if PARSE_RINGBUFFER_INCREASE_SIZE < PARSE_RINGBUFFER_MIN_AVAILABLE
# error PARSE_RINGBUFFER_INCREASE_SIZE may noy be less than PARSE_RINGBUFFER_MIN_AVAILABLE
#endif
